# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gateway < Formula
  desc "High-performance self-hosted AI gateway (OpenAI-compatible) with routing, retries, and streaming"
  homepage "https://github.com/lunargate-ai/gateway"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.1/gateway_0.0.1_darwin_amd64.tar.gz"
      sha256 "bf3d40a0edbb9c673bbe2b96730bdec52e422b562a815ce60283984dce52da9a"

      def install
        bin.install "lunargate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.1/gateway_0.0.1_darwin_arm64.tar.gz"
      sha256 "a51562c93533cf0d688cb62d5d2ada8cfe6129508716ea035e1011f69acbb4db"

      def install
        bin.install "lunargate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.1/gateway_0.0.1_linux_amd64.tar.gz"
        sha256 "80b1b7ed37e02f747241fa68cff339c0df901a42fb20b6cd9c5caf739ddb9232"

        def install
          bin.install "lunargate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.1/gateway_0.0.1_linux_arm64.tar.gz"
        sha256 "bf5d4cfeae50c1ae816be4c6490d5c89c167ef232f04a37439e22709238b9de4"

        def install
          bin.install "lunargate"
        end
      end
    end
  end

  test do
    system "#{bin}/lunargate", "--help"
  end
end
