# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunargate < Formula
  desc "High-performance self-hosted AI gateway (OpenAI-compatible) with routing, retries, and streaming"
  homepage "https://github.com/lunargate-ai/gateway"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.2.3/gateway_0.2.3_darwin_amd64.tar.gz"
      sha256 "46ea916c15147ecf04b90c0ebaf3bc1637ed24731443c4747b9373c3818d8378"

      def install
        bin.install "lunargate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.2.3/gateway_0.2.3_darwin_arm64.tar.gz"
      sha256 "48f7b5525adcdc066c172e4871ecfcd3e75976d1148ba6d63e22fc61b14bcf4b"

      def install
        bin.install "lunargate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.2.3/gateway_0.2.3_linux_amd64.tar.gz"
        sha256 "282e654c87a91681d7a142097e6bd2ea5c2749120bb79cda3889c378a9498c13"

        def install
          bin.install "lunargate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.2.3/gateway_0.2.3_linux_arm64.tar.gz"
        sha256 "be455b083bb479a057d7d22bc8e65b0e8f0df4193fdf8a296717f67612b86486"

        def install
          bin.install "lunargate"
        end
      end
    end
  end

  test do
    system "#{bin}/lunargate", "--help"
  end
end
