# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunargate < Formula
  desc "High-performance self-hosted AI gateway (OpenAI-compatible) with routing, retries, and streaming"
  homepage "https://github.com/lunargate-ai/gateway"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.1.0/gateway_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1fdb99d399368618e0deea902f0f66771fa69304f55d49328b84f95cdcdbad4"

      def install
        bin.install "lunargate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.1.0/gateway_0.1.0_darwin_arm64.tar.gz"
      sha256 "04bc480fcd62c46a273b6a1f828b0911e535ecc698396231184aef1605d10295"

      def install
        bin.install "lunargate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.1.0/gateway_0.1.0_linux_amd64.tar.gz"
        sha256 "a61281cce48db74a601e3df114dc41ea53650845393dc1d33da02353b0cc8c61"

        def install
          bin.install "lunargate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.1.0/gateway_0.1.0_linux_arm64.tar.gz"
        sha256 "4ed95cf77c9d26dde10913d7edbffdbc98f979f7f963deb1992e54f08e0d4aea"

        def install
          bin.install "lunargate"
        end
      end
    end
  end

  test do
    system "#{bin}/lunargate", "--help"
  end
end
