# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunargate < Formula
  desc "High-performance self-hosted AI gateway (OpenAI-compatible) with routing, retries, and streaming"
  homepage "https://github.com/lunargate-ai/gateway"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.5/gateway_0.0.5_darwin_amd64.tar.gz"
      sha256 "797e7838408338bb1b5eeb0844a5f570a978dc4885f63eb3e51404d7312ba09f"

      def install
        bin.install "lunargate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.5/gateway_0.0.5_darwin_arm64.tar.gz"
      sha256 "564f9a198366fcdc33b4fd7bf5513e399d55ae644b78dc37c3ad20f55fdbd02b"

      def install
        bin.install "lunargate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.5/gateway_0.0.5_linux_amd64.tar.gz"
        sha256 "73d55eee0ebdb65ce09707e5d5edc567314646f39b25dc23e7725a340758273a"

        def install
          bin.install "lunargate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lunargate-ai/gateway/releases/download/v0.0.5/gateway_0.0.5_linux_arm64.tar.gz"
        sha256 "e74a8cbca54e7c7e849f6249a2dbf18eccc417ae4dcdb18d8c021c4201a32d29"

        def install
          bin.install "lunargate"
        end
      end
    end
  end

  test do
    system "#{bin}/lunargate", "--help"
  end
end
